#
# fort package - general FastTransform class definition ----
#

#' `FastTransform` class
#'
#' @description General specification of the type of objects generated by `fort()`, which correspond
#'   to structured linear transforms. Useful objects of this class must be also part of a subclass
#'   which extends this one with a specific implementation (e.g., `FastTransformFFT2`).
#'
#' @details It is generally \emph{not} recommended that the fields and methods described here are used
#'   directly, unless you need to minimize validation overhead when using \emph{pre-validated} inputs.
#'   Instead, you should use `fort()` and the typical S3 methods for matrices (`%*%.FastTransform`,
#'   `t().FastTransform`, `solve().FastTransform`, etc.).
#'
#' @field inverse Logical. Indicates whether the object currently represents a forward or
#'   inverse transform.
#' @field invertible Logical. Indicates whether the inverse transform can also be expressed as a
#'   `FastTransform` object.
#' @field dim_in Dimensionality of the input for the forward transform.
#' @field dim_out Dimensionality of the output for the forward transform.
#' @field blocksize Dimensionality of the internal transformation (always a power of 2).
#' @field fwd_par List of parameters used in the forward transform.
#' @field fwd_mtrx Cached matrix representation of the forward transform.
#' @field rev_par List of parameters used in the inverse transform.
#' @field rev_mtrx Cached matrix representation of the inverse transform.
#' @field fort_type String indicating the type of structured transform being used.
#' @field cache_matrix Logical. Indicates whether to cache calculated matrices or not (default is `TRUE`).
#' @field logdet List with cached determinants of the forward and inverse transforms
#' @export
FastTransform <- R6::R6Class(classname="FastTransform",
                             public=list(

                               inverse=FALSE,
                               invertible=FALSE,
                               dim_in=NULL,
                               dim_out=NULL,
                               blocksize=NULL,

                               #' @description Function that performs the forward transform.
                               #'   Do \emph{not} call this directly unless you know what you are doing:
                               #'   use the `FastTransform$evaluate()` method instead.
                               #' @param x Input matrix of the \emph{correct} dimensionality
                               #' @return A matrix with the same number of columns as `x`.
                               fwd_eval=function(x) NULL,
                               fwd_par=NULL,
                               fwd_mtrx=NULL,

                               #' @description Function that performs the inverse transform.
                               #'   Do \emph{not} call this directly unless you know what you are doing:
                               #'   use the `FastTransform$evaluate()` method instead.
                               #' @param x Input matrix of the \emph{correct} dimensionality
                               #' @return A matrix with the same number of columns as `x`.
                               rev_eval=function(x) NULL,
                               rev_par=NULL,
                               rev_mtrx=NULL,

                               #' @description Function that calculates and caches the parameters
                               #'   for the inverse transform. Do not call this directly unless you
                               #'   know what you are doing. If you need the inverse transform, use
                               #'   the `FastTransform$get_inverse()` method instead.
                               calculate_rev_par=function() NULL,
                               fort_type=NULL,
                               cache_matrix=TRUE,
                               logdet=list(fwd=NULL,rev=NULL),

                               #' @description Raw object creation function. Note that calling this
                               #' function does \emph{not} result in a useful object. Instead, you
                               #' should call the `fort()` function.
                               #' @param dim_in Dimensionality of the input for the forward transform.
                               #' @param dim_out Dimensionality of the output for the forward transform.
                               #' @param blocksize Dimensionality of the internal transformation
                               #'   (\emph{must} be a power of 2).
                               #' @return A matrix with the same number of columns as `x`.
                               initialize=function(dim_in,dim_out,blocksize) {
                                 # do nothing
                               },

                               #' @description Evaluates the result of applying the transform represented
                               #'   by this object on an input matrix `x`. It is important that the
                               #'   provided matrix has compatible dimensionality since \emph{no input
                               #'   validation is performed}.
                               #' @param x Input matrix with correct dimensionality.
                               #' @return A matrix with the same number of columns as `x`.
                               evaluate=function(x) {
                                 if (self$inverse) {
                                   # evaluate inverse
                                   if (self$invertible) {
                                     # evaluate inverse normally
                                     self$rev_eval(x)
                                   } else {
                                     # use matrix form to calculate inverse
                                     self$as_matrix() %*% x
                                   }
                                 } else {
                                   # evaluate transform normally
                                   self$fwd_eval(x)
                                 }
                               },

                               #' @description Returns the number of columns of the linear
                               #'   transform represented by this object.
                               #' @return A numeric value.
                               get_ncol=function() {
                                 if (self$inverse) {
                                   self$dim_out
                                 } else {
                                   self$dim_in
                                 }
                               },

                               #' @description Returns the number of rows of the linear
                               #'   transform represented by this object.
                               #' @return A numeric value.
                               get_nrow=function() {
                                 if (self$inverse) {
                                   self$dim_in
                                 } else {
                                   self$dim_out
                                 }
                               },

                               #' @description Returns the dimensions of the linear
                               #'   transform represented by this object.
                               #' @return A numeric vector with length 2.
                               get_dim=function() {
                                 if (self$inverse) {
                                   c(self$dim_in,self$dim_out)
                                 } else {
                                   c(self$dim_out,self$dim_in)
                                 }
                               },

                               #' @description Returns the number of parameters required to represent
                               #'   the linear transform represented by this object.
                               #' @return A numeric value.
                               get_n_par=function() {
                                 if (self$inverse && (!self$invertible)) {
                                   # look at the number of parameters in the matrix representation
                                   self$dim_in * self$dim_out
                                 } else {
                                   # look at the number of parameters in the forward transform
                                   length(unlist(self$fwd_par))
                                 }
                               },

                               #' @description Returns a new `FastTransform` object that represents
                               #'   the inverse transform of the transform represented by this
                               #'   object.
                               #' @return A new object of type `FastTransform`.
                               get_inverse=function() {
                                 if (self$inverse) {
                                   # if already in inverse form...
                                   # just clone object and set inverse to FALSE
                                   new_object <- self$clone()
                                   new_object$inverse <- FALSE
                                 } else {
                                   # otherwise...
                                   if (self$invertible) {
                                     # check if inverse parameters are already calculated
                                     if (is.null(self$rev_par)) {
                                       # calculate and cache parameters for
                                       # inverse transformation
                                       self$calculate_rev_par()
                                     }
                                   } else {
                                     # get self as matrix
                                     mtrx <- self$as_matrix()
                                     # apply pseudoinverse and store result
                                     # (even if cache_matrix is FALSE)
                                     self$rev_mtrx <- MASS::ginv(mtrx)
                                   }

                                   # clone object and set inverse to TRUE
                                   new_object <- self$clone()
                                   new_object$inverse <- TRUE
                                 }
                                 # return an inverted copy of the object
                                 new_object
                               },

                               #' @description Returns either a `FastTransform` object that represents
                               #'   the transpose of the transform represented by this object (if
                               #'   the value of the `invertible` field is `TRUE`), or an equivalent
                               #'   matrix.
                               #' @return Either an new object of type `FastTransform` or a matrix.
                               get_transpose=function() {
                                 if (self$invertible) {
                                   # transpose is simply the inverse
                                   self$get_inverse()
                                 } else {
                                   # transpose can only be obtained by converting to matrix
                                   # warn user if the t() helper function was used
                                   t(self$as_matrix())
                                 }
                               },

                               #' @description Returns information on the determinant of the
                               #'   transform represented by this object. Fails if `dim_in != dim_out`.
                               #'   The modulus of the determinant is provided in log scale.
                               #' @return The same type of object returned by `determinant.matrix`.
                               get_logdet=function() {
                                 logdet <- self$logdet
                                 # check if pre-cached
                                 if (self$inverse) {
                                   if (!is.null(logdet$rev)) return(logdet$rev)
                                 } else {
                                   if (!is.null(logdet$fwd)) return(logdet$fwd)
                                 }
                                 # check if square transform
                                 is_square <- (self$dim_in == self$dim_out)
                                 if (!is_square) stop("you can only calculate the determinant of a square matrix")
                                 # calculate
                                 mtrx <- self$as_matrix()
                                 calculated_logdet <- determinant.matrix(mtrx, logarithm = TRUE)
                                 # cache
                                 if (self$inverse) {
                                   (self$logdet$rev <- calculated_logdet)
                                 } else {
                                   (self$logdet$fwd <- calculated_logdet)
                                 }
                               },

                               #' @description Returns norm of the matrix equivalent to the linear
                               #'   transform represented by this object.
                               #' @param type String indicating the type of matrix norm to calculate,
                               #'   using the same convention as `base::norm` (default is "o", which
                               #'   corresponds to the maximum absolute column sum).
                               #' @return A numeric value.
                               get_norm=function(type="o") {
                                 get_type <- tolower(substr(type,1,1))
                                 mtrx <- self$as_matrix()
                                 switch(get_type,
                                        o=norm(mtrx,type="o"),
                                        i=norm(mtrx,type="i"),
                                        f=norm(mtrx,type="f"),
                                        m=norm(mtrx,type="m"),
                                        `1`=norm(mtrx,type="o"),
                                        `2`=norm(mtrx,type="2"),
                                        stop(paste0("invalid `type` when calling",
                                                    " get_norm(); use instead one",
                                                    "of: o, i, f, m, 1, 2"))

                                        )
                               },

                               #' @description Returns norms of the rows (or columns) or the matrix
                               #'   equivalent to the linear transform represented by this object.
                               #' @param type String indicating the type of matrix norm to calculate,
                               #'   using a convention compatible with `base::norm` (default is "2",
                               #'   which corresponds to the Euclidian norm; use "o" for L1 norm,
                               #'   "m" for Inf norm).
                               #' @param by The norms of the rows are calculated by default (`by = 1`).
                               #'   To calculate the norms of columns instead, use `by = 2`.
                               #' @return A vector of numeric values.
                               get_norm_margin=function(type="2",by=1) {
                                 get_type <- tolower(substr(type,1,1))
                                 mtrx <- self$as_matrix()
                                 switch(get_type,
                                        m=apply(abs(mtrx),by,max),
                                        i=apply(abs(mtrx),by,max),
                                        o=apply(abs(mtrx),by,sum),
                                        f=sqrt(apply(mtrx^2,by,sum)),
                                        `1`=apply(abs(mtrx),by,sum),
                                        `2`=sqrt(apply(mtrx^2,by,sum)),
                                        stop(paste0("invalid `type` when calling",
                                                    " get_norm(); use instead one",
                                                    "of: o, i, f, m, 1, 2"))
                                        )
                               },

                               #' @description Returns the matrix equivalent to the transform
                               #'   represented by this object.
                               #' @return A matrix.
                               as_matrix=function() {
                                 is_inverse <- self$inverse

                                 if (is_inverse) {
                                   # check for cached matrix
                                   if (!is.null(self$rev_mtrx)) return(self$rev_mtrx)
                                 } else {
                                   # check for cached matrix
                                   if (!is.null(self$fwd_mtrx)) return(self$fwd_mtrx)
                                 }

                                 # no cached matrix, so calculate it
                                 if (is_inverse && (!self$invertible)) {
                                   # get fwd_mtrx
                                   fwd_mtrx <- self$fwd_mtrx
                                   if (is.null(fwd_mtrx)) {
                                     self$inverse <- FALSE
                                     fwd_mtrx <- self$as_matrix()
                                     self$inverse <- TRUE
                                   }
                                   # get pseudoinverse and cache it
                                   out_mtrx <- MASS::ginv(mtrx)
                                   self$rev_mtrx <- out_mtrx
                                 } else {
                                   # transform canonical basis
                                   canonical_basis <- diag(self$get_ncol())
                                   out_mtrx <- self$evaluate(canonical_basis)
                                   # check if result should be cached
                                   if (self$cache_matrix) {
                                     if (is_inverse) {
                                       self$rev_mtrx <- out_mtrx
                                     } else {
                                       self$fwd_mtrx <- out_mtrx
                                     }
                                   }
                                 }

                                 # return calculated matrix
                                 out_mtrx
                               },

                               #' @description Prints terse information about the object.
                               #' @return The object itself (invisibly).
                               print=function() {
                                 is_inverse <- self$inverse
                                 s_ <- .get_printing_symbols()
                                 s_arrow <- s_[["arrows"]][1 + as.numeric(is_inverse)]
                                 s_real <- s_[["real"]]
                                 s_times <- s_[["times"]]
                                 tag_ <- ifelse(is_inverse,
                                                "fort linear operation (inverted): ",
                                                "fort linear operation: ")
                                 cur_dim_in <- self$dim_in
                                 cur_dim_out <- self$dim_out
                                 cur_blocksize <- self$blocksize
                                 cur_type <- self$fort_type
                                 input_dim <- ifelse(is_inverse,cur_dim_in,cur_dim_out)
                                 buffer_ <- paste0(tag_,
                                                   s_real, "^", cur_dim_in, " ", s_arrow, " [")
                                 if (is_inverse && (!self$invertible)) {
                                   buffer_ <- paste0(buffer_,"slow linear transform")
                                 } else {
                                   if (cur_dim_in != cur_blocksize) {
                                     buffer_ <- paste0(buffer_, s_real, "^", cur_blocksize, " ", s_arrow, " ")
                                   }
                                   buffer_ <- paste0(buffer_, cur_type)
                                   if (cur_dim_out != cur_blocksize) {
                                     buffer_ <- paste0(buffer_, " ", s_arrow, " ", s_real, "^", cur_blocksize)
                                   }
                                 }

                                 buffer_ <- paste0(buffer_, "] ", s_arrow, " ", s_real, "^", cur_dim_out)

                                 cat(buffer_) # print information
                                 # return self
                                 invisible(self)
                               },

                               #' @description Prints verbose information about the object.
                               #' @return The object itself (invisibly).
                               summary=function() {
                                 self$print()
                                 s_ <- .get_printing_symbols()
                                 s_times <- s_[["times"]]
                                 cur_dim_in <- self$get_ncol()
                                 cur_dim_out <- self$get_nrow()
                                 is_inverse <- self$inverse
                                 if (is_inverse && (!self$invertible)) {
                                   cur_type_line <- "slow linear inverse transform (matrix multiplication)"
                                 } else {
                                   cur_type <- self$fort_type
                                   if (is_inverse) cur_type <- paste0("inverted ",cur_type)
                                   cur_type <- paste0(cur_type,"/",class(self)[1])
                                   cur_type_line <- paste0(cur_type," (with an internal blocksize of ",self$blocksize,")")
                                 }

                                 cat(paste0("\n ~ input: ",cur_dim_in,"-dimensional column vector(s) (",cur_dim_in," ",s_times," N matrix)\n"))
                                 cat(paste0(" ~ output: ",cur_dim_out,"-dimensional column vector(s) (",cur_dim_out," ",s_times," N matrix)\n"))
                                 cat(paste0(" ~ type: ",cur_type_line,"\n"))
                                 cat(paste0(" ~ number of parameters: ",self$get_n_par()," (instead of ",cur_dim_in*cur_dim_out,")\n"))
                                 cat(paste0(" ~ usage: apply transform to X via: W %**% X, if W is this object and X is a ",cur_dim_in," ",s_times," N matrix"))
                                 # return self
                                 invisible(self)
                               }

                             )
)
