# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Applies forward FFT2-type fort transform
#'
#' @param X_Re numeric matrix for real component of input
#' @param X_Im numeric matrix for imaginary component of input
#' @param s1 numeric vector for real component of sc1
#' @param s2 numeric vector for imaginary component of sc1
#' @param s3 numeric vector for real component of sc2
#' @param s4 numeric vector for imaginary component of sc2
#' @param s5 numeric vector for real component of sc3
#' @param s6 numeric vector for imaginary component of sc3
#' @return transformed numeric matrix
#' @noRd
.FORT_CPP_FFT2_fwd <- function(X_Re, X_Im, s1, s2, s3, s4, s5, s6) {
    .Call(`_fort_FORT_CPP_FFT2_fwd`, X_Re, X_Im, s1, s2, s3, s4, s5, s6)
}

#' Applies reverse FFT2-type fort transform
#'
#' @param X_Re numeric matrix for real component of input
#' @param X_Im numeric matrix for imaginary component of input
#' @param s1 numeric vector for real component of sc3i
#' @param s2 numeric vector for imaginary component of sc3i
#' @param s3 numeric vector for real component of sc2i
#' @param s4 numeric vector for imaginary component of sc2i
#' @param s5 numeric vector for real component of sc1i
#' @param s6 numeric vector for imaginary component of sc1i
#' @return transformed numeric matrix
#' @noRd
.FORT_CPP_FFT2_rev <- function(X_Re, X_Im, s1, s2, s3, s4, s5, s6) {
    .Call(`_fort_FORT_CPP_FFT2_rev`, X_Re, X_Im, s1, s2, s3, s4, s5, s6)
}

